name: Deploy Prochord
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. 현재 디렉토리 파일 리스트 확인 (디버깅 용도)
      - name: List files in current directory
        run: ls -la

      # 4. Docker 이미지 빌드 및 테스트 실행 후 push
      - name: Build Docker image for testing
        run: |
          docker buildx build --platform linux/amd64 --load --tag 5hseok/OutOfCity-server:0.0.1 -f ./Dockerfile .

      # 5. Docker Hub로 이미지 push
      - name: Push Docker image to Docker Hub
        run: |
          docker push 5hseok/OutOfCity-server:0.0.1

      # 6. EC2에 SSH로 연결하여 배포
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Docker Compose 파일이 있는 디렉토리로 이동
            cd /home/ubuntu

            # Docker 이미지 pull 및 컨테이너 재실행
            sudo docker pull 5hseok/OutOfCity-server:0.0.1

            # 기존 컨테이너 종료 및 제거
            if [ "$(sudo docker ps -q -f name=spring_app)" ]; then
              sudo docker stop spring_app && sudo docker rm spring_app
            fi

            # Docker Compose를 사용하여 컨테이너 실행
            sudo docker-compose down
            sudo docker-compose up --build -d

            # spring_app 컨테이너의 로그 출력
            sudo docker logs spring_app
